name: Add environment

on:
  workflow_dispatch:
    inputs:
      port_payload:
        description: 'Port JSON payload'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  actions: read

env:
  GH_ORG: ${{ github.repository_owner }}

jobs:
  add-environment:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      RUN_ID: ${{ fromJson(inputs.port_payload).runId }}
    steps:
      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ env.GH_ORG }}

      - name: Export token
        shell: bash
        run: |
          set -euo pipefail; IFS=$'\n\t'
          echo "GITHUB_TOKEN=${{ steps.app-token.outputs.token }}" >> "$GITHUB_ENV"
          echo "GH_TOKEN=${{ steps.app-token.outputs.token }}" >> "$GITHUB_ENV"

      - name: Configure git user
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        shell: bash
        run: |
          set -euo pipefail; IFS=$'\n\t'
          user_id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email "${user_id}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com"

      - name: Configure git remote
        shell: bash
        run: |
          set -euo pipefail; IFS=$'\n\t'
          if [ -d .git ]; then
            git remote set-url origin "https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${GITHUB_REPOSITORY}.git"
          fi

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Parse payload
        id: parse
        shell: bash
        run: |
          set -euo pipefail; IFS=$'\n\t'
          PAYLOAD='${{ inputs.port_payload }}'
            echo "$PAYLOAD" | jq -e '.runId,
            .request_identifier,
            .github_repository,
            .environment_identifier,
            .service_identifier,
            .managed_identity_client_id,
            .environment_location,
            .environment_resource_group,
            .environment_type' >/dev/null
          {
            echo "run_id=$(echo "$PAYLOAD" | jq -r .runId)"
            echo "github_repository=$(echo "$PAYLOAD" | jq -r .github_repository)"
            echo "state_file_container=$(echo "$PAYLOAD" | jq -r '.state_file_container // ""')"
            echo "environment_type=$(echo "$PAYLOAD" | jq -r .environment_type)"
            echo "env_name=$(echo "$PAYLOAD" | jq -r .environment_identifier)"
            echo "request_identifier=$(echo "$PAYLOAD" | jq -r .request_identifier)"
            echo "environment_identifier=$(echo "$PAYLOAD" | jq -r .environment_identifier)"
            echo "service_identifier=$(echo "$PAYLOAD" | jq -r .service_identifier)"
            echo "managed_identity_client_id=$(echo "$PAYLOAD" | jq -r .managed_identity_client_id)"
            echo "environment_location=$(echo "$PAYLOAD" | jq -r .environment_location)"
            echo "environment_resource_group=$(echo "$PAYLOAD" | jq -r .environment_resource_group)"
            echo "state_file_resource_group=$(echo "$PAYLOAD" | jq -r '.state_file_resource_group // ""')"
            echo "state_file_storage_account=$(echo "$PAYLOAD" | jq -r '.state_file_storage_account // ""')"
          } >> "$GITHUB_OUTPUT"
      - name: Validate environment identifier
        shell: bash
        run: |
          set -euo pipefail; IFS=$'\n\t'
          if [ -z "${{ steps.parse.outputs.environment_identifier }}" ]; then
            echo "::error::environment_identifier is required"
            exit 1
          fi
      - name: Derive identifiers
        shell: bash
        run: |
          set -euo pipefail; IFS=$'\n\t'
          {
            echo "REPO_NAME=$(basename ${{ steps.parse.outputs.github_repository }})"
            echo "ENV_NAME=${{ steps.parse.outputs.environment_identifier }}"
            echo "WORKLOAD_ID=$(basename ${{ steps.parse.outputs.github_repository }})-${{ steps.parse.outputs.environment_identifier }}"
            } >> "$GITHUB_ENV"

      - name: Port log – start
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ steps.parse.outputs.run_id }}
          logMessage: "Starting environment addition"

      - name: Clone target repository
        shell: bash
        run: |
          set -euo pipefail; IFS=$'\n\t'
          git clone "https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ steps.parse.outputs.github_repository }}.git" service-repo

      - name: Create feature branch
        env:
          GH_TOKEN: ${{ env.GH_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail; IFS=$'\n\t'
          TARGET_BRANCH="add-env-${{ steps.parse.outputs.environment_identifier }}-${{ github.run_id }}"
          cd service-repo
          git checkout -b "$TARGET_BRANCH"
          echo "TARGET_BRANCH=$TARGET_BRANCH" >> "$GITHUB_ENV"

      - name: Add environment files
        shell: bash
        run: |
          set -euo pipefail; IFS=$'\n\t'
          env_dir="service-repo/env/${{ steps.parse.outputs.environment_identifier }}"
          mkdir -p "$env_dir"
          {
            if [ -n "${{ steps.parse.outputs.state_file_resource_group }}" ]; then
              echo "resource_group_name  = \"${{ steps.parse.outputs.state_file_resource_group }}\""
            else
              echo "# resource_group_name  = \"\""
            fi
            if [ -n "${{ steps.parse.outputs.state_file_storage_account }}" ]; then
              echo "storage_account_name = \"${{ steps.parse.outputs.state_file_storage_account }}\""
            else
              echo "# storage_account_name = \"\""
            fi
            if [ -n "${{ steps.parse.outputs.state_file_container }}" ]; then
              echo "container_name       = \"${{ steps.parse.outputs.state_file_container }}\""
            else
              echo "# container_name       = \"\""
            fi
            echo "key                  = \"${{ steps.parse.outputs.environment_identifier }}.tfstate\""
          } > "$env_dir/${{ steps.parse.outputs.environment_identifier }}.state.config"
          cat > "$env_dir/${{ steps.parse.outputs.environment_identifier }}.tfvars" <<EOF
          environment    = "${{ steps.parse.outputs.environment_identifier }}"
          location       = "${{ steps.parse.outputs.environment_location }}"
          resource_group = "${{ steps.parse.outputs.environment_resource_group }}"
          EOF
      - name: Commit environment files
        env:
          GH_TOKEN: ${{ env.GH_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail; IFS=$'\n\t'
          cd service-repo
          git add env/${{ steps.parse.outputs.environment_identifier }}
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add environment '${{ steps.parse.outputs.environment_identifier }}'"
            git push origin "$TARGET_BRANCH"
            echo "CHANGED=1" >> "$GITHUB_ENV"
          fi

      - name: Open pull request
        if: env.CHANGED == '1'
        env:
          GH_TOKEN: ${{ env.GH_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail; IFS=$'\n\t'
          cd service-repo
          default_branch=$(gh repo view --json defaultBranchRef --jq .defaultBranchRef.name)
          gh pr create \
            --head "$TARGET_BRANCH" \
            --base "$default_branch" \
            --title "Add environment '${{ steps.parse.outputs.environment_identifier }}'" \
            --body "Automated addition of environment '${{ steps.parse.outputs.environment_identifier }}'."

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        working-directory: repositories/modules/environment
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ env.GH_ORG }}
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        shell: bash
        run: |
          set -euo pipefail; IFS=$'\n\t'
          terraform init \
            -backend-config=../../../service-repo/env/${{ steps.parse.outputs.environment_identifier }}/${{ steps.parse.outputs.environment_identifier }}.state.config \
            -backend-config=use_azuread_auth=true

      - name: Terraform apply
        working-directory: repositories/modules/environment
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ env.GH_ORG }}
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        shell: bash
        run: |
          set -euo pipefail; IFS=$'\n\t'
          terraform apply -auto-approve \
            -var "repository=${{ env.REPO_NAME }}" \
            -var "environment_name=${{ steps.parse.outputs.environment_identifier }}" \
            -var "managed_identity_client_id=${{ steps.parse.outputs.managed_identity_client_id }}" \
            -var "owner=${{ env.GH_ORG }}"
          terraform output -json > tf.json
      - name: Update repository manifest
        shell: bash
        run: |
          set -euo pipefail; IFS=$'\n\t'
          pip install pyyaml >/dev/null
          NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          export REPO_NAME ENV_NAME NOW
          python - <<'PY' >> "$GITHUB_ENV"
          import os, importlib.util
          spec = importlib.util.spec_from_file_location('mu', 'scripts/manifest-utils.py')
          mu = importlib.util.module_from_spec(spec); spec.loader.exec_module(mu)
          repo=os.environ['REPO_NAME']
          env=os.environ['ENV_NAME']
          ts=os.environ['NOW']
          path=f"repositories/manifests/{repo}.yaml"
          changed = mu.upsert_repo_environment(path, env, ts)
          print(f"MANIFEST={path}")
          print(f"CHANGED={'1' if changed else '0'}")
          print(f"COMMIT_MESSAGE=Add environment '{env}' to repo '{repo}'")
          PY

      - name: Commit manifest
        if: ${{ env.CHANGED == '1' }}
        uses: ./.github/actions/commit-yaml
        with:
          path: ${{ env.MANIFEST }}
          message: ${{ env.COMMIT_MESSAGE }}

      - name: Upsert workload in Port
        if: ${{ success() }}
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: UPSERT
          identifier: ${{ env.WORKLOAD_ID }}
          title: ${{ env.WORKLOAD_ID }}
          blueprint: workload
          relations: |
            { "environment": "${{ steps.parse.outputs.environment_identifier }}", "service": "${{ steps.parse.outputs.service_identifier }}" }
          runId: ${{ steps.parse.outputs.run_id }}
          status: success
          logMessage: "Linked service '${{ steps.parse.outputs.service_identifier }}' with environment '${{ steps.parse.outputs.environment_identifier }}'"

      - name: Mark link request complete
        if: ${{ success() }}
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: UPSERT
          blueprint: link_environment_request
          identifier: ${{ steps.parse.outputs.request_identifier }}
          properties: |
            { "status": "Complete" }

      - name: Report success to Port
        if: ${{ success() }}
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ steps.parse.outputs.run_id }}
          status: SUCCESS
          summary: "Environment '${{ steps.parse.outputs.environment_identifier }}' added to ${{ steps.parse.outputs.github_repository }}"

      - name: Report failure to Port
        if: ${{ failure() }}
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ steps.parse.outputs.run_id }}
          status: FAILURE
          summary: "Environment '${{ steps.parse.outputs.environment_identifier }}' failed"
