name: CI

permissions:
  contents: read
  checks: write
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-check
          level: warning
          fail_level: warning

  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - repositories/modules/repo
          - teams/modules/team
          - modules/github-initial-config
          - repositories
          - teams
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-tflint@v1
        with:
          working_directory: ${{ matrix.directory }}
          reporter: github-check
          fail_level: warning
          level: warning
          tflint_config: 
      - uses: reviewdog/action-terraform-validate@v1
        with:
          workdir: ${{ matrix.directory }}
          reporter: github-check
          level: warning
          fail_level: warning
