name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - repositories/modules/repo
          - teams/modules/team
          - repositories
          - teams
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        run: terraform init -backend=false
        working-directory: ${{ matrix.directory }}
      - name: Terraform validate
        run: terraform validate
        working-directory: ${{ matrix.directory }}
