# Inputs:
#   port_payload: Port JSON payload
#   mock: When true, skip side-effecting steps (default: false)
# Port payload keys used (see docs/port-payload-contracts.md):
# - runId
# - blueprint
# - requestedBy
# - properties.port_product_identifier
# - properties.port_service_identifier
# - properties.port_service_name
# - properties.port_service_description
# - properties.port_cost_centre
# - properties.port_owning_team
# - properties.port_owning_team_identifier
# - properties.port_repo_visibility
# - properties.port_owning_team_slug
# - properties.port_owner_team_permission
# - properties.cookiecutter_template
# - properties.cookiecutter_user_context
name: Create repository from template

on:
  workflow_dispatch:
    inputs:
      port_payload:
        description: 'Port JSON payload'
        required: true
        type: string
      mock:
        description: 'Run in mock mode, skipping side effects'
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  id-token: write
  actions: read

env:
  GH_ORG: ${{ secrets.GH_ORG }}

jobs:
  validation:
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.parse.outputs.run_id }}
      blueprint: ${{ steps.parse.outputs.blueprint }}
      requested_by: ${{ steps.parse.outputs.requested_by }}
      repo_name: ${{ steps.parse.outputs.repo_name }}
      description: ${{ steps.parse.outputs.description }}
      repo_visibility: ${{ steps.parse.outputs.repo_visibility }}
      owning_team_slug: ${{ steps.parse.outputs.owning_team_slug }}
      owner_team_permission: ${{ steps.parse.outputs.owner_team_permission }}
      cookiecutter_template: ${{ steps.parse.outputs.cookiecutter_template }}
      cookiecutter_context: ${{ steps.parse.outputs.cookiecutter_context }}
      product_identifier: ${{ steps.parse.outputs.product_identifier }}
      product_cost_centre: ${{ steps.parse.outputs.product_cost_centre }}
      created_at: ${{ steps.parse.outputs.created_at }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Parse payload
        id: parse
        run: |
          PAYLOAD='${{ inputs.port_payload }}'
          echo "$PAYLOAD" | jq -e '.runId,
            .properties.port_product_identifier,
            .properties.port_service_identifier,
            .properties.port_service_name,
            .properties.port_service_description,
            .properties.port_cost_centre,
            .properties.port_owning_team,
            .properties.port_owning_team_identifier,
            .properties.port_repo_visibility,
            .properties.port_owning_team_slug,
            .properties.port_owner_team_permission,
            .properties.cookiecutter_template,
            .properties.cookiecutter_user_context' >/dev/null

          PORT_CONTEXT=$(echo "$PAYLOAD" | jq -c '.properties | with_entries(select(.key | startswith("port_")))')
          USER_CONTEXT=$(echo "$PAYLOAD" | jq -c .properties.cookiecutter_user_context)
          COMBINED_CONTEXT=$(jq -c -n --argjson port "$PORT_CONTEXT" --argjson user "$USER_CONTEXT" '$port + $user')
          {
            echo "RUN_ID=$(echo "$PAYLOAD" | jq -r .runId)"
            echo "BLUEPRINT=$(echo "$PAYLOAD" | jq -r .blueprint)"
            echo "REQUESTED_BY=$(echo "$PAYLOAD" | jq -r .requestedBy)"
            echo "REPO_NAME=$(echo "$PAYLOAD" | jq -r .properties.port_service_identifier)"
            echo "DESCRIPTION=$(echo "$PAYLOAD" | jq -r .properties.port_service_description)"
            echo "REPO_VISIBILITY=$(echo "$PAYLOAD" | jq -r .properties.port_repo_visibility)"
            echo "OWNING_TEAM_SLUG=$(echo "$PAYLOAD" | jq -r .properties.port_owning_team_slug)"
            echo "OWNER_TEAM_PERMISSION=$(echo "$PAYLOAD" | jq -r .properties.port_owner_team_permission)"
            echo "COOKIECUTTER_TEMPLATE=$(echo "$PAYLOAD" | jq -r .properties.cookiecutter_template)"
            echo "COOKIECUTTER_CONTEXT=$COMBINED_CONTEXT"
            echo "PRODUCT_IDENTIFIER=$(echo "$PAYLOAD" | jq -r .properties.port_product_identifier)"
            echo "PRODUCT_COST_CENTRE=$(echo "$PAYLOAD" | jq -r .properties.port_cost_centre)"
            echo "CREATED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          } >> "$GITHUB_ENV"
          {
            echo "run_id=$(echo "$PAYLOAD" | jq -r .runId)"
            echo "blueprint=$(echo "$PAYLOAD" | jq -r .blueprint)"
            echo "requested_by=$(echo "$PAYLOAD" | jq -r .requestedBy)"
            echo "repo_name=$(echo "$PAYLOAD" | jq -r .properties.port_service_identifier)"
            echo "description=$(echo "$PAYLOAD" | jq -r .properties.port_service_description)"
            echo "repo_visibility=$(echo "$PAYLOAD" | jq -r .properties.port_repo_visibility)"
            echo "owning_team_slug=$(echo "$PAYLOAD" | jq -r .properties.port_owning_team_slug)"
            echo "owner_team_permission=$(echo "$PAYLOAD" | jq -r .properties.port_owner_team_permission)"
            echo "cookiecutter_template=$(echo "$PAYLOAD" | jq -r .properties.cookiecutter_template)"
            echo "cookiecutter_context=$COMBINED_CONTEXT"
            echo "product_identifier=$(echo "$PAYLOAD" | jq -r .properties.port_product_identifier)"
            echo "product_cost_centre=$(echo "$PAYLOAD" | jq -r .properties.port_cost_centre)"
            echo "created_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          } >> "$GITHUB_OUTPUT"

      - name: Mock run notice
        if: ${{ inputs.mock }}
        run: |
          echo "Mock run: skipping side-effecting steps"

      - name: Get GitHub App token
        id: app-token
        uses: ./.github/actions/get-gh-app-token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ secrets.GH_ORG }}

      - name: Get bot user ID
        id: get-user-id
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"

      - name: Configure git user
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - name: Validate repository name
        run: ./scripts/validate-name.sh "$GH_ORG" "$REPO_NAME"

  env-setup:
    needs: validation
    runs-on: ubuntu-latest
    env:
      RUN_ID: ${{ needs.validation.outputs.run_id }}
      BLUEPRINT: ${{ needs.validation.outputs.blueprint }}
      REQUESTED_BY: ${{ needs.validation.outputs.requested_by }}
      REPO_NAME: ${{ needs.validation.outputs.repo_name }}
      DESCRIPTION: ${{ needs.validation.outputs.description }}
      REPO_VISIBILITY: ${{ needs.validation.outputs.repo_visibility }}
      OWNING_TEAM_SLUG: ${{ needs.validation.outputs.owning_team_slug }}
      OWNER_TEAM_PERMISSION: ${{ needs.validation.outputs.owner_team_permission }}
      COOKIECUTTER_TEMPLATE: ${{ needs.validation.outputs.cookiecutter_template }}
      COOKIECUTTER_CONTEXT: ${{ needs.validation.outputs.cookiecutter_context }}
      PRODUCT_IDENTIFIER: ${{ needs.validation.outputs.product_identifier }}
      PRODUCT_COST_CENTRE: ${{ needs.validation.outputs.product_cost_centre }}
      CREATED_AT: ${{ needs.validation.outputs.created_at }}
    outputs:
      manifest: ${{ steps.draft.outputs.manifest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Draft manifest
        id: draft
        run: |
          mkdir -p repositories/manifests
          context_lines=$(echo "$COOKIECUTTER_CONTEXT" | jq -r 'to_entries[] | "      \(.key): \"\(.value)\""')
          cat > "repositories/manifests/${REPO_NAME}.yaml" <<MANIFEST
          apiVersion: v1
          kind: GitHubRepository
          metadata:
            name: $REPO_NAME
            createdAt: "$CREATED_AT"
            createdBy: "$REQUESTED_BY"
          spec:
            description: "$DESCRIPTION"
            visibility: "$REPO_VISIBILITY"
            ownerTeam:
              slug: "$OWNING_TEAM_SLUG"
              permission: "$OWNER_TEAM_PERMISSION"
            template:
              source: "$COOKIECUTTER_TEMPLATE"
              context:
          ${context_lines}
          status:
            phase: creating
          MANIFEST
          echo "MANIFEST=repositories/manifests/${REPO_NAME}.yaml" >> "$GITHUB_ENV"
          echo "manifest=repositories/manifests/${REPO_NAME}.yaml" >> "$GITHUB_OUTPUT"

      - name: Azure login
        if: ${{ !inputs.mock }}
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        if: ${{ !inputs.mock }}
        uses: hashicorp/setup-terraform@v3

  create-repo:
    needs: [validation, env-setup]
    runs-on: ubuntu-latest
    env:
      RUN_ID: ${{ needs.validation.outputs.run_id }}
      REPO_NAME: ${{ needs.validation.outputs.repo_name }}
      DESCRIPTION: ${{ needs.validation.outputs.description }}
      REPO_VISIBILITY: ${{ needs.validation.outputs.repo_visibility }}
      OWNING_TEAM_SLUG: ${{ needs.validation.outputs.owning_team_slug }}
      OWNER_TEAM_PERMISSION: ${{ needs.validation.outputs.owner_team_permission }}
    outputs:
      repo_id: ${{ steps.apply.outputs.repo_id }}
      html_url: ${{ steps.apply.outputs.html_url }}
      ssh_url: ${{ steps.apply.outputs.ssh_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get GitHub App token
        uses: ./.github/actions/get-gh-app-token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ secrets.GH_ORG }}

      - name: Terraform init
        if: ${{ !inputs.mock }}
        working-directory: repositories/modules/repo
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.AZURE_RESOURCE_GROUP }}" \
            -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT }}" \
            -backend-config="container_name=${{ secrets.AZURE_STORAGE_CONTAINER }}" \
            -backend-config="key=repos/${REPO_NAME}.tfstate" \
            -backend-config="use_azuread_auth=true"

      - name: Terraform apply
        id: apply
        if: ${{ !inputs.mock }}
        working-directory: repositories/modules/repo
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          terraform apply -auto-approve \
            -var "org=$GH_ORG" \
            -var "repo_name=$REPO_NAME" \
            -var "description=$DESCRIPTION" \
            -var "visibility=$REPO_VISIBILITY" \
            -var "owner_team_slug=$OWNING_TEAM_SLUG" \
            -var "owner_perm=$OWNER_TEAM_PERMISSION"
          terraform output -json > tf.json
          repo_id=$(jq -r .repo_id.value tf.json)
          html_url=$(jq -r .html_url.value tf.json)
          ssh_url=$(jq -r .ssh_url.value tf.json)
          {
            echo "repo_id=$repo_id"
            echo "html_url=$html_url"
            echo "ssh_url=$ssh_url"
          } >> "$GITHUB_ENV"
          {
            echo "repo_id=$repo_id"
            echo "html_url=$html_url"
            echo "ssh_url=$ssh_url"
          } >> "$GITHUB_OUTPUT"

      - name: Cleanup Terraform
        if: ${{ always() && !inputs.mock }}
        working-directory: repositories/modules/repo
        run: rm -rf .terraform terraform.tfstate*

  scaffold-service:
    needs: [validation, create-repo]
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ needs.validation.outputs.repo_name }}
      COOKIECUTTER_TEMPLATE: ${{ needs.validation.outputs.cookiecutter_template }}
      COOKIECUTTER_CONTEXT: ${{ needs.validation.outputs.cookiecutter_context }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get GitHub App token
        uses: ./.github/actions/get-gh-app-token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ secrets.GH_ORG }}

      - name: Scaffold repository
        if: ${{ !inputs.mock }}
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        run: |
          pip install cookiecutter
          tmpdir=$(mktemp -d)
          context_args=$(echo "$COOKIECUTTER_CONTEXT" | jq -r 'to_entries | map("\(.key)=\(.value|@sh)") | join(" ")')
          eval set -- "$context_args"
          cookiecutter "$COOKIECUTTER_TEMPLATE" --no-input --output-dir "$tmpdir" "$@"
          generated_dir=$(ls -d "$tmpdir"/*)
          cd "$generated_dir"
          git init
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GH_ORG}/${REPO_NAME}.git"
          git add .
          git commit -m "Initial commit from template"
          git branch -M main
          git push origin main

  configure-repo:
    needs: [validation, scaffold-service]
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ needs.validation.outputs.repo_name }}
      COOKIECUTTER_TEMPLATE: ${{ needs.validation.outputs.cookiecutter_template }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get GitHub App token
        uses: ./.github/actions/get-gh-app-token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ secrets.GH_ORG }}

      - name: Configure repository
        if: ${{ !inputs.mock }}
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          GH_SECRETS: ${{ toJson(secrets) }}
        run: |
          set -euo pipefail
          git clone "$COOKIECUTTER_TEMPLATE" template-repo
          mkdir tf-config
          yq -o=json template-repo/.provisioning/repository-config.yml > tf-config/config.json
          jq --argjson s "$GH_SECRETS" '
            [.secrets // [] | .[] | select(.source != "none") |
              {key: .name,
               value: (if .source == "workflow_secret"
                       then $s[.ref]
                       else env[.ref]
                      end)}] | from_entries
          ' tf-config/config.json > tf-config/secret-values.json
          cat > tf-config/main.tf <<'TF'
          terraform {
            required_providers {
              github = {
                source  = "integrations/github"
                version = "~> 6.0"
              }
            }
          }

          provider "github" {
            owner = var.owner
          }

          module "initial_config" {
            source        = "../modules/github-initial-config"
            owner         = var.owner
            repo          = var.repo
            config        = jsondecode(file("${path.module}/config.json"))
            secret_values = jsondecode(file("${path.module}/secret-values.json"))
          }

          variable "owner" { type = string }
          variable "repo"  { type = string }
          TF
          cd tf-config
          terraform init
          terraform apply -auto-approve -var owner="${GH_ORG}" -var repo="${REPO_NAME}"

      - name: Cleanup Terraform (configuration)
        if: ${{ always() && !inputs.mock }}
        run: rm -rf tf-config/.terraform tf-config/terraform.tfstate*

      - name: Mock run notice (configuration)
        if: ${{ inputs.mock }}
        run: |
          echo "Mock run: skipping repository configuration"

  tidyup:
    needs: [validation, env-setup, create-repo, configure-repo]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    env:
      RUN_ID: ${{ needs.validation.outputs.run_id }}
      REQUESTED_BY: ${{ needs.validation.outputs.requested_by }}
      REPO_NAME: ${{ needs.validation.outputs.repo_name }}
      DESCRIPTION: ${{ needs.validation.outputs.description }}
      REPO_VISIBILITY: ${{ needs.validation.outputs.repo_visibility }}
      OWNING_TEAM_SLUG: ${{ needs.validation.outputs.owning_team_slug }}
      OWNER_TEAM_PERMISSION: ${{ needs.validation.outputs.owner_team_permission }}
      COOKIECUTTER_TEMPLATE: ${{ needs.validation.outputs.cookiecutter_template }}
      COOKIECUTTER_CONTEXT: ${{ needs.validation.outputs.cookiecutter_context }}
      CREATED_AT: ${{ needs.validation.outputs.created_at }}
      MANIFEST: ${{ needs.env-setup.outputs.manifest }}
      repo_id: ${{ needs.create-repo.outputs.repo_id }}
      html_url: ${{ needs.create-repo.outputs.html_url }}
      ssh_url: ${{ needs.create-repo.outputs.ssh_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get GitHub App token
        uses: ./.github/actions/get-gh-app-token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ secrets.GH_ORG }}

      - name: Finalize manifest
        if: ${{ !inputs.mock }}
        run: |
          context_lines=$(echo "$COOKIECUTTER_CONTEXT" | jq -r 'to_entries[] | "      \(.key): \"\(.value)\""')
          cat > "$MANIFEST" <<MANIFEST
          apiVersion: v1
          kind: GitHubRepository
          metadata:
            name: $REPO_NAME
            createdAt: "$CREATED_AT"
            createdBy: "$REQUESTED_BY"
          spec:
            description: "$DESCRIPTION"
            visibility: "$REPO_VISIBILITY"
            ownerTeam:
              slug: "$OWNING_TEAM_SLUG"
              permission: "$OWNER_TEAM_PERMISSION"
            template:
              source: "$COOKIECUTTER_TEMPLATE"
              context:
          $context_lines
          status:
            id: "$repo_id"
            htmlUrl: "$html_url"
            sshUrl: "$ssh_url"
            phase: active
          MANIFEST

      - name: Commit manifest
        if: ${{ !inputs.mock }}
        uses: ./.github/actions/commit-yaml
        with:
          path: ${{ env.MANIFEST }}
          message: Add repository '${{ env.REPO_NAME }}' (automated via Port)

      - name: Report failure to Port
        if: ${{ failure() && !inputs.mock }}
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ env.RUN_ID }}
          status: failure
          logMessage: 'Workflow failed'

      - name: Mark manifest failed
        if: ${{ failure() && !inputs.mock }}
        run: |
          if [ -f "$MANIFEST" ]; then
            sed -i 's/phase: creating/phase: failed/' "$MANIFEST"
          fi
