# Inputs:
#   port_payload: Port JSON payload
#   mock: When true, skip side-effecting steps (default: false)
name: Revoke team access from repository

on:
  workflow_dispatch:
    inputs:
      port_payload:
        description: "Port JSON payload"
        required: true
        type: string
      mock:
        description: "Run in mock mode, skipping side effects"
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  actions: read
  id-token: write

env:
  GH_ORG: ${{ secrets.GH_ORG }}

jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Parse payload
        run: |
          set -euo pipefail
          PAYLOAD='${{ inputs.port_payload }}'
          echo "$PAYLOAD" | jq -e '.runId,.blueprint,.properties.repo_name,.properties.team_slug' >/dev/null
          RUN_ID=$(echo "$PAYLOAD" | jq -r .runId)
          BLUEPRINT=$(echo "$PAYLOAD" | jq -r .blueprint)
          REQUESTED_BY=$(echo "$PAYLOAD" | jq -r .requestedBy)
          REPO_NAME=$(echo "$PAYLOAD" | jq -r .properties.repo_name | xargs)
          TEAM_SLUG=$(echo "$PAYLOAD" | jq -r .properties.team_slug | tr '[:upper:]' '[:lower:]' | xargs)
          MIRROR=$(echo "$PAYLOAD" | jq -r '.properties.mirror_on_team_manifest // false')
          if [[ "$MIRROR" != "true" && "$MIRROR" != "false" ]]; then
            echo "mirror_on_team_manifest must be boolean" >&2; exit 1; fi
          NOTE=$(echo "$PAYLOAD" | jq -r '.properties.note // ""')
          NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          {
            echo "RUN_ID=$RUN_ID"
            echo "BLUEPRINT=$BLUEPRINT"
            echo "REQUESTED_BY=$REQUESTED_BY"
            echo "REPO_NAME=$REPO_NAME"
            echo "TEAM_SLUG=$TEAM_SLUG"
            echo "MIRROR=$MIRROR"
            echo "NOTE=$NOTE"
            echo "NOW=$NOW"
          } >> "$GITHUB_ENV"

      - name: Mock run notice
        if: ${{ inputs.mock == 'true' }}
        run: |
          echo "Mock run: skipping side-effecting steps"

      - name: Get GitHub App token
        id: app-token
        uses: ./.github/actions/get-gh-app-token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          installation_id: ${{ secrets.GH_APP_INSTALLATION_ID }}

      - name: Validate repository and team
        run: |
          set -euo pipefail
          repo_resp=$(gh api "repos/${GH_ORG}/${REPO_NAME}" 2>/tmp/repo_err) || { cat /tmp/repo_err >&2; exit 1; }
          if [ "$(echo "$repo_resp" | jq -r .archived)" = "true" ]; then
            echo "Repository ${REPO_NAME} is archived" >&2; exit 1; fi
          gh api "orgs/${GH_ORG}/teams/${TEAM_SLUG}" >/dev/null 2>&1 || { echo "Team ${TEAM_SLUG} not found" >&2; exit 1; }
          if gh api "/orgs/${GH_ORG}/teams/${TEAM_SLUG}/repos/${GH_ORG}/${REPO_NAME}" >/tmp/rel.json 2>/tmp/rel.err; then
            HAS_ACCESS=true
          else
            if grep -q 'Not Found' /tmp/rel.err; then
              HAS_ACCESS=false
            else
              cat /tmp/rel.err >&2; exit 1
            fi
          fi
          echo "HAS_ACCESS=$HAS_ACCESS" >> "$GITHUB_ENV"

      - name: Revoke access
        if: ${{ inputs.mock == 'false' && env.HAS_ACCESS == 'true' }}
        run: |
          set -euo pipefail
          for i in 1 2; do
            if gh api --method DELETE "/orgs/${GH_ORG}/teams/${TEAM_SLUG}/repos/${GH_ORG}/${REPO_NAME}"; then
              break
            fi
            if [ "$i" -eq 2 ]; then exit 1; fi
            sleep 5
          done
          if gh api "/orgs/${GH_ORG}/teams/${TEAM_SLUG}/repos/${GH_ORG}/${REPO_NAME}" >/dev/null 2>&1; then
            echo "Team still has access after revoke" >&2; exit 1; fi
          echo "PORT_MESSAGE=removed access" >> "$GITHUB_ENV"

      - name: Set no-op message
        if: env.HAS_ACCESS != 'true'
        run: echo "PORT_MESSAGE=no-op (team had no access)" >> "$GITHUB_ENV"

      - name: Build commit message
        run: |
          msg="Remove team '${TEAM_SLUG}' from repo '${REPO_NAME}' (via Port)"
          if [ -n "$NOTE" ]; then
            msg="$msg - $NOTE"
          fi
          echo "COMMIT_MESSAGE=$msg" >> "$GITHUB_ENV"

      - name: Update manifests
        run: |
          set -euo pipefail
          pip install pyyaml >/dev/null
          python - <<'PY' >> "$GITHUB_ENV"
          import os, json, yaml, importlib.util
          spec = importlib.util.spec_from_file_location('mu', 'scripts/manifest-utils.py')
          mu = importlib.util.module_from_spec(spec); spec.loader.exec_module(mu)
          repo=os.environ['REPO_NAME']; slug=os.environ['TEAM_SLUG']; ts=os.environ['NOW']
          repo_path=f"repositories/manifests/{repo}.yaml"
          repo_changed = mu.remove_repo_team(repo_path, slug, ts)
          if repo_changed:
              mu.touch_last_updated(repo_path, ts)
          with open(repo_path) as f: data=yaml.safe_load(f) or {}
          print(f"REPO_MANIFEST={repo_path}")
          print("TEAM_LIST="+json.dumps([t['slug'] for t in data.get('teams',[])], separators=(',',':')))
          print(f"REPO_CHANGED={'1' if repo_changed else '0'}")
          if os.environ.get('MIRROR') == 'true':
              team=os.environ['TEAM_SLUG']; repo=os.environ['REPO_NAME']
              team_path=f"teams/manifests/{team}.yaml"
              team_changed = mu.remove_team_repo(team_path, repo, ts)
              if team_changed:
                  mu.touch_last_updated(team_path, ts)
              with open(team_path) as f: tdata=yaml.safe_load(f) or {}
              print(f"TEAM_MANIFEST={team_path}")
              print("TEAM_REPO_LIST="+json.dumps([r['name'] for r in tdata.get('repositories',[])], separators=(',',':')))
              print(f"TEAM_CHANGED={'1' if team_changed else '0'}")
          PY

      - name: Upsert repository in Port
        if: ${{ inputs.mock == 'false' }}
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: UPSERT
          identifier: ${{ env.REPO_NAME }}
          title: ${{ env.REPO_NAME }}
          blueprint: ${{ env.BLUEPRINT }}
          relations: |
            { "teams": ${{ env.TEAM_LIST }} }
          runId: ${{ env.RUN_ID }}
          status: success
          logMessage: ${{ env.PORT_MESSAGE }}

      - name: Upsert team in Port
        if: ${{ inputs.mock == 'false' && env.MIRROR == 'true' }}
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: UPSERT
          identifier: ${{ env.TEAM_SLUG }}
          title: ${{ env.TEAM_SLUG }}
          blueprint: githubTeam
          relations: |
            { "repositories": ${{ env.TEAM_REPO_LIST }} }
          runId: ${{ env.RUN_ID }}
          status: success
          logMessage: ${{ env.PORT_MESSAGE }}

      - name: Stage team manifest
        if: ${{ inputs.mock == 'false' && env.MIRROR == 'true' && env.TEAM_CHANGED == '1' }}
        run: git add "${{ env.TEAM_MANIFEST }}"

      - name: Commit manifest(s)
        if: ${{ inputs.mock == 'false' }}
        uses: ./.github/actions/commit-yaml
        with:
          path: ${{ env.REPO_MANIFEST }}
          message: ${{ env.COMMIT_MESSAGE }}

      - name: Report failure to Port
        if: ${{ failure() && inputs.mock == 'false' }}
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ env.RUN_ID }}
          status: failure
          logMessage: 'Workflow failed'

# Tests:
# - Happy path: team had maintain -> removed; manifests updated.
# - No-op: team had no access -> success; manifests unchanged or cleaned.
# - Repo missing: fail fast; Port failure reported.
# - Team missing: fail fast; Port failure reported.
# - Archived repo: fail with explicit message.
# - Mirror disabled: only repo manifest updated.
# - Mirror enabled: repo and team manifests updated.
